#define _ANDROID
#define TEXTURE_FRAME_INTERPOLATION

uniform sampler2D Texture0;

void main(
	float4 colorVarying : COLOR,
	float4 uv : TEXCOORD0,
	float frameFactor : TEXCOORD1,
	float4 out gl_FragColor : COLOR
) {
	float4 color=colorVarying;
	
	float4 txt=tex2D(Texture0,uv.xy);
#ifdef TEXTURE_FRAME_INTERPOLATION
	float4 txt2=tex2D(Texture0,uv.zw);
	txt=lerp(txt,txt2,frameFactor);
#endif

	color*=txt;
	gl_FragColor=color;
}
